# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
    BITHUMB_NEXUS_PREFIX: public-docker.bithumb.com
    SECURE_ANALYZERS_PREFIX: public-gitlab-docker.bithumb.com/gitlab-org/security-products/analyzers
    SAST_EXCLUDED_ANALYZERS: ''
    SAST_EXCLUDED_PATHS: spec, test, tests, tmp
    SCAN_KUBERNETES_MANIFESTS: 'false'
    BITHUMB_RUNNER_TAG_NAME: bithumb_bs_sast
    BITHUMB_PROJECT_REF_BRANCH: master
stages:
    - test

workflow:
    rules:
        - if: '$CI_COMMIT_REF_NAME == $BITHUMB_PROJECT_REF_BRANCH'
        - when: never

sast:
    stage: test
    artifacts:
        reports:
            sast: gl-sast-report.json
        expire_in: 1 week
    rules:
        - when: never
    script:
        - echo "$CI_JOB_NAME is used for configuration only, and its script should not be
          excuted"
        - exit 1
    tags:
        - '${BITHUMB_RUNNER_TAG_NAME}'
.sast-analyzer:
    extends: sast
    allow_failure: true
    script:
        - chmod 755 *
        - '/analyzer run'
    tags:
        - '${BITHUMB_RUNNER_TAG_NAME}'
eslint-sast:
    extends: .sast-analyzer
    image:
        name: '$SAST_ANALYZER_IMAGE'
    variables:
        SAST_ANALYZER_IMAGE_TAG: 2
        SAST_ANALYZER_IMAGE: '$SECURE_ANALYZERS_PREFIX/eslint:$SAST_ANALYZER_IMAGE_TAG'
    rules:
        - if: $SAST_DISABLED
          when: never
        - if: $SAST_EXCLUDED_ANALYZERS =~ /eslint/
          when: never
        - if: $CI_COMMIT_BRANCH
          exists:
              - '**/*.html'
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.ts'
              - '**/*.tsx'
    tags:
        - '${BITHUMB_RUNNER_TAG_NAME}'
